version: '3'
services:
  dodo-api:
    restart: unless-stopped
    depends_on:
      - dodo_db_postgres
    env_file:
      - "../config/dodo/.env"
#    environment:
#      - SPRING_PROFILES_ACTIVE=${PROFILE}
#      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
    ports:
      - '8080:8080'
    networks:
      - my_dodo_network
    container_name: dodo-api

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  dodo_db_postgres:
    restart: on-failure
    image: postgres
    container_name: dodo_db_postgres
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    volumes:
      - db_data_dodo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dodo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KG41&?uh5^ww)4q
    ports:
      - '5433:5432'
    networks:
      - my_dodo_network

volumes:
  grafana-storage:
  db_data:
  db_data_dodo:
networks:
  my_dodo_network:
    driver: bridge
#    external: true
